#  -------------------
#
#  First action v1.0
#  Yurii
#
#  -------------------

name: GitHub-Actions-Basics

on:
  push:
    branches: 
      - main

jobs:
  ololo-mgs:
    runs-on: ubuntu-latest 
    steps:
    - name: print msg
      run: echo "Hey, YOU! HELLO WORLD OLOLO!"

  shmalolo-msg:
    runs-on: ubuntu-latest
    needs: [ololo-mgs]
    steps:
    - name: print msg
      run: echo "Hey, YOU! HELLO WORLD SHMA!"    








      
